/*
 * 作成日: 2009/04/03
 */
package jp.ac.fit.asura.naoji.v4l2;

/**
 * @author $Author: sey $
 *
 * @version $Id: $
 *
 */
public enum V4L2Control {
	V4L2_CID_BRIGHTNESS, V4L2_CID_CONTRAST, V4L2_CID_SATURATION, V4L2_CID_HUE, V4L2_CID_VFLIP, V4L2_CID_HFLIP, V4L2_CID_RED_BALANCE, V4L2_CID_BLUE_BALANCE, V4L2_CID_GAIN, V4L2_CID_HCENTER, V4L2_CID_VCENTER, V4L2_CID_AUTOGAIN, V4L2_CID_AUTO_WHITE_BALANCE, V4L2_CID_EXPOSURE, V4L2_CID_CAM_INIT, V4L2_CID_SHARPNESS, V4L2_CID_AUTOEXPOSURE, V4L2_CID_EXPOSURE_CORRECTION, V4L2_CID_AEC_ALGORITHM;
}
