/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ac_fit_asura_naoji_jal_JALMotion */

#ifndef _Included_jp_ac_fit_asura_naoji_jal_JALMotion
#define _Included_jp_ac_fit_asura_naoji_jal_JALMotion
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1create
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _isDefinedJoint
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1isDefinedJoint
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _defineJoint
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1defineJoint
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _removeJoint
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1removeJoint
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _isRunning
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1isRunning
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _wait
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1wait
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _clearFootsteps
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1clearFootsteps
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _doMove
 * Signature: (J[I[F[FI)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1doMove
  (JNIEnv *, jclass, jlong, jintArray, jfloatArray, jfloatArray, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _doMoveAll
 * Signature: (J[F[FI)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1doMoveAll
  (JNIEnv *, jclass, jlong, jfloatArray, jfloatArray, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _getAngle
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1getAngle
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _getBodyAngles
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1getBodyAngles
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _getBodyJointNames
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1getBodyJointNames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _getJointStiffness
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1getJointStiffness
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _gotoAngle
 * Signature: (JIFFI)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1gotoAngle
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _gotoBodyAngles
 * Signature: (J[FFI)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1gotoBodyAngles
  (JNIEnv *, jclass, jlong, jfloatArray, jfloat, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _gotoBodyStiffness
 * Signature: (JFFI)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1gotoBodyStiffness
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _gotoJointStiffness
 * Signature: (JIFFI)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1gotoJointStiffness
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _setBodyStiffness
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1setBodyStiffness
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _setJointStiffness
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1setJointStiffness
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _setWalkConfig
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1setWalkConfig
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _setWalkExtraConfig
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1setWalkExtraConfig
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _stop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1stop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _turn
 * Signature: (JFI)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1turn
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _walkArc
 * Signature: (JFFI)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1walkArc
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _walkIsActive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1walkIsActive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _walkStraight
 * Signature: (JFI)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1walkStraight
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMotion
 * Method:    _walkSideways
 * Signature: (JFI)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMotion__1walkSideways
  (JNIEnv *, jclass, jlong, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
