/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ac_fit_asura_naoji_jal_JALModule */

#ifndef _Included_jp_ac_fit_asura_naoji_jal_JALModule
#define _Included_jp_ac_fit_asura_naoji_jal_JALModule
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
