/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ac_fit_asura_naoji_jal_JDCM */

#ifndef _Included_jp_ac_fit_asura_naoji_jal_JDCM
#define _Included_jp_ac_fit_asura_naoji_jal_JDCM
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
/*
 * Class:     jp_ac_fit_asura_naoji_jal_JDCM
 * Method:    _create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_ac_fit_asura_naoji_jal_JDCM__1create
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JDCM
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JDCM__1dispose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JDCM
 * Method:    _isRunning
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_jal_JDCM__1isRunning
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JDCM
 * Method:    _wait
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_jal_JDCM__1wait
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JDCM
 * Method:    _createAlias
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JDCM__1createAlias
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JDCM
 * Method:    _getTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_jal_JDCM__1getTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JDCM
 * Method:    _set
 * Signature: (JLjava/lang/String;I[F[I)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JDCM__1set
  (JNIEnv *, jclass, jlong, jstring, jint, jfloatArray, jintArray);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JDCM
 * Method:    _setTimeMixed
 * Signature: (JII[[F[[I)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JDCM__1setTimeMixed
  (JNIEnv *, jclass, jlong, jint, jint, jobjectArray, jobjectArray);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JDCM
 * Method:    _setTimeSeparate
 * Signature: (JII[F[I)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JDCM__1setTimeSeparate
  (JNIEnv *, jclass, jlong, jint, jint, jfloatArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
