/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ac_fit_asura_naoji_v4l2_Videodev */

#ifndef _Included_jp_ac_fit_asura_naoji_v4l2_Videodev
#define _Included_jp_ac_fit_asura_naoji_v4l2_Videodev
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _createVideodev
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1createVideodev
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _disposeBuffers
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1disposeBuffers
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _disposeImage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1disposeImage
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _getSelectedCamera
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1getSelectedCamera
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _getControl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1getControl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _getFormat
 * Signature: (ILjp/ac/fit/asura/naoji/v4l2/V4L2PixelFormat;)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1getFormat
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _isSupportedControl
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1isSupportedControl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _isSupportedFormat
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1isSupportedFormat
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _isSupportedFPS
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1isSupportedFPS
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _requestBuffers
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1requestBuffers
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _queryBuffer
 * Signature: (II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1queryBuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _selectCamera
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1selectCamera
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _setControl
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1setControl
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _setFormat
 * Signature: (ILjp/ac/fit/asura/naoji/v4l2/V4L2PixelFormat;)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1setFormat
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _setFPS
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1setFPS
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _start
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1start
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_v4l2_Videodev
 * Method:    _retrieveImage
 * Signature: (ILjp/ac/fit/asura/naoji/v4l2/V4L2Buffer;)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_v4l2_Videodev__1retrieveImage
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
