/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ac_fit_asura_naoji_i2c_I2Cdev */

#ifndef _Included_jp_ac_fit_asura_naoji_i2c_I2Cdev
#define _Included_jp_ac_fit_asura_naoji_i2c_I2Cdev
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_ac_fit_asura_naoji_i2c_I2Cdev
 * Method:    _createI2Cdev
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_i2c_I2Cdev__1createI2Cdev
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_ac_fit_asura_naoji_i2c_I2Cdev
 * Method:    _destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_i2c_I2Cdev__1destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_i2c_I2Cdev
 * Method:    _getSelectedCamera
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_i2c_I2Cdev__1getSelectedCamera
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_i2c_I2Cdev
 * Method:    _init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_i2c_I2Cdev__1init
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_i2c_I2Cdev
 * Method:    _selectCamera
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jp_ac_fit_asura_naoji_i2c_I2Cdev__1selectCamera
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
