/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ac_fit_asura_naoji_NaojiModule */

#ifndef _Included_jp_ac_fit_asura_naoji_NaojiModule
#define _Included_jp_ac_fit_asura_naoji_NaojiModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_ac_fit_asura_naoji_NaojiModule
 * Method:    _createJALBroker
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_ac_fit_asura_naoji_NaojiModule__1createJALBroker
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_ac_fit_asura_naoji_NaojiModule
 * Method:    _isRunning
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_NaojiModule__1isRunning
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_NaojiModule
 * Method:    _wait
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_NaojiModule__1wait
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
