/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ac_fit_asura_naoji_jal_JALMemory */

#ifndef _Included_jp_ac_fit_asura_naoji_jal_JALMemory
#define _Included_jp_ac_fit_asura_naoji_jal_JALMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMemory
 * Method:    _create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMemory__1create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMemory
 * Method:    defineKey
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMemory_defineKey
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMemory
 * Method:    undefineKey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMemory_undefineKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMemory
 * Method:    _wait
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMemory__1wait
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMemory
 * Method:    _isRunning
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMemory__1isRunning
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
