/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ac_fit_asura_naoji_jal_JALProxy */

#ifndef _Included_jp_ac_fit_asura_naoji_jal_JALProxy
#define _Included_jp_ac_fit_asura_naoji_jal_JALProxy
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALProxy
 * Method:    _create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_ac_fit_asura_naoji_jal_JALProxy__1create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALProxy
 * Method:    _isRunning
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_jal_JALProxy__1isRunning
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALProxy
 * Method:    _wait
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_ac_fit_asura_naoji_jal_JALProxy__1wait
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
