/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_ac_fit_asura_naoji_jal_JALMemory */

#ifndef _Included_jp_ac_fit_asura_naoji_jal_JALMemory
#define _Included_jp_ac_fit_asura_naoji_jal_JALMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_ac_fit_asura_naoji_jal_JALMemory
 * Method:    _create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jp_ac_fit_asura_naoji_jal_JALMemory__1create
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
